# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidgetItem
from PySide2.QtWidgets import QHeaderView, QAbstractItemView
from src.GUI.InsertWindow import *
from src.GUI.Meniu_comanda import Meniu_comanda
from src.GUI.db_controler import *

class Ui_MainWindow(object):
    def __init__(self,mainWindow):
        self.controler = Controler()
        self.insert_window = None #ui_InsertWindow(QtWidgets.QWidget(),self.controler)
        self.command_menu = None
        self.setupUi(mainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 581)#518
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 210, 1158, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 160, 171, 28))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem(" ")
        self.comboBox.setItemText(0, " ")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.activated.connect(self.block_insert)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 160, 111, 21))

        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(120, 490, 93, 28))
        self.pushButton.setObjectName("pushButton")

        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 490, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(320, 490, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 871, 71))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)

        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(20, 490, 93, 28))
        font = QtGui.QFont()
        font.setStrikeOut(False)

        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        if self.comboBox.currentText() == 'Comenzi' or self.comboBox.currentText() == 'Detalii_comanda':
            self.pushButton_4.hide()

        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 160, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        #self.pushButton_5.clicked.connect(lambda: self.controler.generic_print(self.comboBox.currentText))

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 26))
        self.menubar.setObjectName("menubar")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        MainWindow.setStatusTip(_translate("MainWindow", "Selectare tabela de afisat"))

        self.tableWidget.setStatusTip(_translate("MainWindow", "Tabela curenta"))

        self.comboBox.setStatusTip(_translate("MainWindow", "Selectare tabela de afisat"))
        self.comboBox.setItemText(0, _translate("MainWindow", "..."))
        self.comboBox.setItemText(1, _translate("MainWindow", "Angajati"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Detalii_angajat"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Departamente"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Clienti"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Comenzi"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Detalii_comanda"))
        self.comboBox.setItemText(7, _translate("MainWindow", "Produse"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Categorii_produse"))

        self.label.setStatusTip(_translate("MainWindow", "Selectare tabela de afisat"))
        self.label.setText(_translate("MainWindow", "Select table:"))

        self.pushButton.setStatusTip(_translate("MainWindow", "Actualizare inregistrare in tabela"))
        self.pushButton.setText(_translate("MainWindow", "Update"))

        self.pushButton_2.setStatusTip(_translate("MainWindow", "Stergere inregistrare in tabela"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete"))

        self.pushButton_3.setStatusTip(_translate("MainWindow", "Initiere comanda"))
        self.pushButton_3.setText(_translate("MainWindow", "Comanda"))
        self.pushButton_3.clicked.connect(self.display_command_menu)
        self.label_2.setText(_translate("MainWindow", "Gestiunea firmei care se ocupa cu vanzarea materialelor de constructii"))

        self.pushButton_4.setStatusTip(_translate("MainWindow", "Inserare inregistrare in tabela"))
        self.pushButton_4.setText(_translate("MainWindow", "Insert"))


        self.pushButton_4.clicked.connect(self.display_insert_menu)


        self.pushButton_5.setText(_translate("MainWindow", "Display"))
        #self.pushButton_5.clicked.connect(lambda: self.controler.generic_print(self.comboBox.currentText()))
        #if self.comboBox.currentText() != "...":
            #print(self.comboBox.currentText())
        self.pushButton_5.clicked.connect(lambda: self.show_table(self.comboBox.currentText()))

    def display_insert_menu(self):
        #print(self.comboBox.currentText() + "1")
        if self.comboBox.currentText() == 'Angajati':
            #print(self.comboBox.currentText() + "2")
            self.insert_window = Angajati_ui_InsertWindow(QtWidgets.QWidget(), self.controler)
        elif self.comboBox.currentText() == 'Detalii_angajat':
            self.insert_window = Detalii_angajat_ui_InsertWindow(QtWidgets.QWidget(), self.controler)
        elif self.comboBox.currentText() == 'Departamente':
            self.insert_window = Departamente_ui_InsertWindow(QtWidgets.QWidget(), self.controler)
        elif self.comboBox.currentText() == 'Clienti':
            self.insert_window = Clienti_ui_InsertWindow(QtWidgets.QWidget(),self.controler)
        elif self.comboBox.currentText() == 'Comenzi':
            self.insert_window = Comenzi_ui_InsertWindow(QtWidgets.QWidget(), self.controler)
        elif self.comboBox.currentText() == 'Detalii_comanda':
            self.insert_window = Detalii_comanda_ui_InsertWindow(QtWidgets.QWidget(), self.controler)
        elif self.comboBox.currentText() == 'Produse':
            self.insert_window = Produse_ui_InsertWindow(QtWidgets.QWidget(), self.controler)
        elif self.comboBox.currentText() == 'Categorii_produse':
            self.insert_window = Categorii_produse_ui_InsertWindow(QtWidgets.QWidget(), self.controler)
        else:
            return

        print(self.comboBox.currentText())
        self.insert_window.show()
        #self.insert_window.show()

    def display_command_menu(self):
        self.command_menu = Meniu_comanda(QtWidgets.QWidget(),self.controler)
        self.command_menu.show()

    def show_table(self,table_name):
        if table_name == "...":
            return

        #self.tableWidget.setEditTriggers(QAbstractItemView.EditingState)
        result1 = self.controler.generic_print(table_name)
        #print(result1)
        result2 = self.controler.get_column_names(table_name)
        #print(result2)

        self.tableWidget.setColumnCount(len(result2))
        self.tableWidget.setRowCount(len(result1))
        self.tableWidget.setHorizontalHeaderLabels(result2)
       # self.tableWidget.horizontalHeader().setSt
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)

        for i in range(0,len(result1)):
            for j in range(0,len(result2)):
                self.tableWidget.setItem(i,j,QTableWidgetItem((str)(result1[i][j])))

        self.tableWidget.resizeColumnsToContents()
        #self.tableWidget.setEditTriggers(QAbstractItemView.NoEditTriggers)

    def block_insert(self):
        if self.comboBox.currentText() == 'Comenzi' or self.comboBox.currentText() == 'Detalii_comanda':
            self.pushButton_4.hide()
        else:
            self.pushButton_4.setVisible(True)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow(mainWindow)
    #ui.setupUi(MainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
