# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QLabel

from src.GUI.db_controler import *

class ui_InsertWindow(object):
    def __init__(self,widget,controler):
        self.widget = widget
        self.controler = controler

        self.data = []

    def setupUi(self, InsertWindow):
        pass

    def retranslateUi(self, InsertWindow):
        pass

    def show(self):
        self.widget.show()

    def insert_data(self):
        pass

    def display_popup(self, exit_code):
        self.popup = QtWidgets.QMainWindow()
        self.popup.resize(518, 172)
        self.popup.show()

        self.text = QLabel(self.popup)
        self.text.setGeometry(QtCore.QRect(30, 10, 171, 71))
        self.text.setText("Eroare")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(24)
        self.text.setFont(font)
        self.text.show()

        self.text2 = QLabel(self.popup)
        self.text2.setGeometry(QtCore.QRect(30, 100, 420, 70))
        if exit_code == -1:
            self.text2.setText("Nu ati completat toate datele obligatorii")
        elif exit_code == -2:
            self.text2.setText("Ati introdus date invalide, reintroduceti")
        elif exit_code == -3:
            self.text2.setText("Nu exista angajat caruia sa ii introduceti detaliile")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(12)
        self.text2.setFont(font)
        self.text2.show()


class Angajati_ui_InsertWindow(ui_InsertWindow):
    def __init__(self,widget,controler):
        super().__init__(widget,controler)
        self.label_title = None
        self.label_instruction = None
        self.line_edit1 = None
        self.line_edit2 = None
        self.combobox = None
        self.label1 = None
        self.label2 = None
        self.label3 = None
        self.submit_button = None

        self.setupUi(self.widget)

    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 285)
        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10,10,91,31))
        self.label_title.setText("Angajati")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10,70,191,20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        self.line_edit1 = QLineEdit(self.widget)
        self.line_edit1.setGeometry(QtCore.QRect(100, 120, 201, 22))
        self.line_edit1.setText("")
        self.line_edit1.show()

        self.label1 = QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label1.setText("Nume:")
        self.label1.show()

        self.line_edit2 = QLineEdit(self.widget)
        self.line_edit2.setGeometry(QtCore.QRect(100, 150, 201, 22))
        self.line_edit2.setText("")
        self.line_edit2.show()

        self.label2 = QLabel(self.widget)
        self.label2.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.label2.setText("Email:")
        self.label2.show()

        self.combobox = QtWidgets.QComboBox(self.widget)
        self.combobox.setGeometry(QtCore.QRect(490, 120, 171, 22))
        self.controler.cursor.execute('SELECT NUME FROM DEPARTAMENTE')
        result = [i[0] for i in self.controler.cursor]

        self.combobox.addItems(result)
        self.combobox.show()

        self.label3 = QLabel(self.widget)
        self.label3.setGeometry(QtCore.QRect(400, 120, 91, 20))
        self.label3.setText("ID_Dept:")
        self.label3.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(580,240,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.show()
        self.submit_button.clicked.connect(self.insert_data)

    def show(self):
        self.widget.show()

    def insert_data(self):
        name = "'"+self.combobox.currentText()+"'"
        self.controler.cursor.execute(f'SELECT id_dept from departamente where nume={name}')

        for i in self.controler.cursor:
            dept_id = i[0]

        self.data = [self.line_edit1.text(), self.line_edit2.text(), dept_id]

        result = self.controler.insert_into_table('Angajati',self.data)
        if result == -1:
            self.display_popup(-1)
        elif result == -2:
            self.display_popup(-2)
        else:
            self.widget.close()
        # verificare nume email si id dept valide

class Detalii_angajat_ui_InsertWindow(ui_InsertWindow):

    def __init__(self,widget,controler):
        super().__init__(widget, controler)
        self.controler.cursor.execute(
            "SELECT nume from angajati where id_angajat not in (select id_angajat from detalii_angajat)")
        result = [i[0] for i in self.controler.cursor]
        print(result)
        if (result == []):
            self.display_popup(-3)
            return



        self.label_title = None
        self.label_instruction = None
        self.combobox = None
        self.line_edit2 = None
        self.line_edit3 = None
        self.line_edit4 = None
        self.line_edit5 = None
        self.line_edit6 = None
        self.line_edit7 = None

        self.label1 = None
        self.label2 = None
        self.label3 = None
        self.label4 = None
        self.label5 = None
        self.label6 = None
        self.label7 = None

        self.submit_button = None
        self.setupUi(self.widget)

    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 304)

        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_title.setText("Detalii angajat")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        # Nume angajat
        self.combobox = QtWidgets.QComboBox(self.widget)
        self.combobox.setGeometry(QtCore.QRect(100, 120, 201, 22))
        self.controler.cursor.execute(
            "SELECT nume from angajati where id_angajat not in (select id_angajat from detalii_angajat)")
        result = [i[0] for i in self.controler.cursor]
        self.combobox.addItems(result)
        #print(self.combobox.currentText())
        self.combobox.show()

        self.label1 = QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label1.setText("Nume:")
        self.label1.show()

        # Data nasterii
        self.line_edit2 = QLineEdit(self.widget)
        self.line_edit2.setGeometry(QtCore.QRect(100, 150, 201, 22))
        self.line_edit2.setPlaceholderText("Format: dd.mm.yyyy")
        self.line_edit2.show()

        self.label2 = QLabel(self.widget)
        self.label2.setGeometry(QtCore.QRect(20, 150, 81, 16))
        self.label2.setText("Data nasterii:")
        self.label2.show()

        # Telefon
        self.line_edit3 = QLineEdit(self.widget)
        self.line_edit3.setGeometry(QtCore.QRect(100, 180, 201, 22))
        self.line_edit3.setText("")
        self.line_edit3.show()

        self.label3 = QLabel(self.widget)
        self.label3.setGeometry(QtCore.QRect(20, 180, 55, 16))
        self.label3.setText("Telefon:")
        self.label3.show()

        # Data angajarii
        self.line_edit4 = QLineEdit(self.widget)
        self.line_edit4.setGeometry(QtCore.QRect(490, 120, 171, 22))
        self.line_edit4.setPlaceholderText("Format: dd.mm.yyyy")
        self.line_edit4.show()

        self.label4 = QLabel(self.widget)
        self.label4.setGeometry(QtCore.QRect(330, 120, 91, 20))
        self.label4.setText("Data angajarii:")
        self.label4.show()

        # Salariu
        self.line_edit5 = QLineEdit(self.widget)
        self.line_edit5.setGeometry(QtCore.QRect(490, 150, 171, 22))
        self.line_edit5.setText("")
        self.line_edit5.show()

        self.label5 = QLabel(self.widget)
        self.label5.setGeometry(QtCore.QRect(330, 150, 91, 20))
        self.label5.setText("Salariu:")
        self.label5.show()

        # Data incheierii contractului
        self.line_edit6 = QLineEdit(self.widget)
        self.line_edit6.setGeometry(QtCore.QRect(490, 180, 171, 22))
        self.line_edit6.setPlaceholderText("Format: dd.mm.yyyy")
        self.line_edit6.show()

        self.label6 = QLabel(self.widget)
        self.label6.setGeometry(QtCore.QRect(330, 180, 161, 20))
        self.label6.setText("Data incheierii contractului:")
        self.label6.show()

        # Adresa domiciliu
        self.line_edit7 = QLineEdit(self.widget)
        self.line_edit7.setGeometry(QtCore.QRect(490, 210, 171, 22))
        self.line_edit7.setText("")
        self.line_edit7.show()

        self.label7 = QLabel(self.widget)
        self.label7.setGeometry(QtCore.QRect(330, 210, 101, 20))
        self.label7.setText("Adresa domiciliu:")
        self.label7.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(570,240,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.clicked.connect(self.insert_data)
        self.submit_button.show()

    def show(self):
        self.controler.cursor.execute(
            "SELECT nume from angajati where id_angajat not in (select id_angajat from detalii_angajat)")
        result = [i[0] for i in self.controler.cursor]
        if (result == []):
            self.display_popup(-3)
            return
        self.widget.show()

    def insert_data(self):
        name = self.combobox.currentText()
        self.controler.cursor.execute(f"SELECT id_angajat from angajati where nume='{name}'")
        print(1)
        #print(self.controler.cursor)
        for i in self.controler.cursor:
            angajat_id = i[0]
            #print(i)

        print(angajat_id)
        self.data = [angajat_id, self.line_edit2.text(), self.line_edit3.text(), self.line_edit4.text(), self.line_edit5.text(), self.line_edit6.text(), self.line_edit7.text()]
        print(self.data)

        result = self.controler.insert_into_table('Detalii_angajat',self.data)
        if result == -1:
            self.display_popup(-1)
        elif result == -2:
            self.display_popup(-2)
        else:
            self.widget.close()

class Departamente_ui_InsertWindow(ui_InsertWindow):
    def __init__(self,widget,controler):
        super().__init__(widget,controler)
        self.setupUi(self.widget)
        self.label_title = None
        self.label_instruction = None

        self.line_edit2 = None

        self.label2 = None
        self.submit_button = None

        self.setupUi(self.widget)

    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 260)

        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_title.setText("Departamente")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        self.line_edit2 = QLineEdit(self.widget)
        self.line_edit2.setGeometry(QtCore.QRect(130, 150, 201, 22))
        self.line_edit2.setText("")
        self.line_edit2.show()

        self.label2 = QLabel(self.widget)
        self.label2.setGeometry(QtCore.QRect(30, 150, 101, 20))
        self.label2.setText("Nume:")
        self.label2.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(570,200,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.clicked.connect(self.insert_data)
        self.submit_button.show()

    def show(self):
        self.widget.show()

    def insert_data(self):
        self.data = [self.line_edit2.text()]
        #print(self.data)
        result = self.controler.insert_into_table('Departamente',self.data)
        if result == -1:
            self.display_popup(-1)
        else:
            self.widget.close()


class Clienti_ui_InsertWindow(ui_InsertWindow):
    def __init__(self,widget,controler):
        super().__init__(widget,controler)
        self.setupUi(self.widget)
        self.label_title = None
        self.label_instruction = None
        self.line_edit1 = None
        self.combobox2 = None
        self.line_edit3 = None
        self.line_edit4 = None
        self.line_edit5 = None

        self.label1 = None
        self.label2 = None
        self.label3 = None
        self.label4 = None
        self.label5 = None

        self.submit_button = None

        self.setupUi(self.widget)
    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 304)
        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_title.setText("Clienti")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        # Nume
        self.line_edit1 = QLineEdit(self.widget)
        self.line_edit1.setGeometry(QtCore.QRect(110, 120, 201, 22))
        self.line_edit1.setText("")
        self.line_edit1.show()

        self.label1 = QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(20, 120, 71, 20))
        self.label1.setText("Nume:")
        self.label1.show()

        # Tip client
        self.combobox2 = QtWidgets.QComboBox(self.widget)
        self.combobox2.setGeometry(QtCore.QRect(110, 150, 201, 22))
        self.combobox2.addItems(['persoana fizica','persoana juridica'])
        self.combobox2.show()

        self.label2 = QLabel(self.widget)
        self.label2.setGeometry(QtCore.QRect(20, 150, 81, 20))
        self.label2.setText("Tip client:")
        self.label2.show()

        # Telefon
        self.line_edit3 = QLineEdit(self.widget)
        self.line_edit3.setGeometry(QtCore.QRect(110, 180, 201, 22))
        self.line_edit3.setText("")
        self.line_edit3.show()

        self.label3 = QLabel(self.widget)
        self.label3.setGeometry(QtCore.QRect(20, 180, 55, 16))
        self.label3.setText("Telefon:")
        self.label3.show()

        # Data ultimei comenzi
        self.line_edit4 = QLineEdit(self.widget)
        self.line_edit4.setGeometry(QtCore.QRect(480, 120, 201, 22))
        self.line_edit4.setText("")
        self.line_edit4.show()

        self.label4 = QLabel(self.widget)
        self.label4.setGeometry(QtCore.QRect(350, 120, 131, 20))
        self.label4.setText("Data ultimei comenzi:")
        self.label4.show()

        # Adresa
        self.line_edit5 = QLineEdit(self.widget)
        self.line_edit5.setGeometry(QtCore.QRect(480, 150, 201, 22))
        self.line_edit5.setText("")
        self.line_edit5.show()

        self.label5 = QLabel(self.widget)
        self.label5.setGeometry(QtCore.QRect(350, 150, 101, 20))
        self.label5.setText("Adresa:")
        self.label5.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(570,240,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.clicked.connect(self.insert_data)
        self.submit_button.show()


    def show(self):
        self.widget.show()

    def insert_data(self):
        client_type = (self.combobox2.currentText())
        client_type = client_type.replace(" ","_")
        print(client_type)

        self.data = [self.line_edit1.text(), client_type, self.line_edit3.text(), self.line_edit4.text(), self.line_edit5.text()]
        print(self.data)
        result = self.controler.insert_into_table('Clienti',self.data)
        if result == -1:
            self.display_popup(-1)
        elif result == -2:
            self.display_popup(-1)
        else:
            self.widget.close()


class Comenzi_ui_InsertWindow(ui_InsertWindow):
    def __init__(self,widget,controler):
        super().__init__(widget,controler)
        self.setupUi(self.widget)
        self.label_title = None
        self.label_instruction = None
        self.line_edit1 = None
        self.line_edit2 = None
        self.line_edit3 = None
        self.line_edit4 = None

        self.label1 = None
        self.label2 = None
        self.label3 = None
        self.label4 = None

        self.submit_button = None

    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 304)

        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.label_title.setText("Comenzi")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        self.line_edit1 = QLineEdit(self.widget)
        self.line_edit1.setGeometry(QtCore.QRect(140, 120, 201, 22))
        self.line_edit1.setText("")
        self.line_edit1.show()

        self.label1 = QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(20, 120, 71, 20))
        self.label1.setText("Data initierii:")
        self.label1.show()

        self.line_edit2 = QLineEdit(self.widget)
        self.line_edit2.setGeometry(QtCore.QRect(140, 150, 201, 22))
        self.line_edit2.setText("")
        self.line_edit2.show()

        self.label2 = QLabel(self.widget)
        self.label2.setGeometry(QtCore.QRect(20, 150, 111, 20))
        self.label2.setText("Status tranzactie:")
        self.label2.show()

        self.line_edit3 = QLineEdit(self.widget)
        self.line_edit3.setGeometry(QtCore.QRect(480, 120, 201, 22))
        self.line_edit3.setText("")
        self.line_edit3.show()

        self.label3 = QLabel(self.widget)
        self.label3.setGeometry(QtCore.QRect(400, 120, 71, 20))
        self.label3.setText("ID client:")
        self.label3.show()

        self.line_edit4 = QLineEdit(self.widget)
        self.line_edit4.setGeometry(QtCore.QRect(480, 150, 201, 22))
        self.line_edit4.setText("")
        self.line_edit4.show()

        self.label4 = QLabel(self.widget)
        self.label4.setGeometry(QtCore.QRect(400, 150, 71, 20))
        self.label4.setText("ID angajat:")
        self.label4.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(585,240,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.show()

    def show(self):
        self.widget.show()


class Detalii_comanda_ui_InsertWindow(ui_InsertWindow):
    def __init__(self,widget,controler):
        super().__init__(widget,controler)
        self.setupUi(self.widget)
        self.label_title = None
        self.label_instruction = None
        self.line_edit1 = None
        self.line_edit2 = None
        self.line_edit3 = None
        self.label1 = None
        self.label2 = None
        self.label3 = None
        self.submit_button = None

    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 304)

        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 168, 31))
        self.label_title.setText("Detalii comanda")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        self.line_edit1 = QLineEdit(self.widget)
        self.line_edit1.setGeometry(QtCore.QRect(140, 120, 201, 22))
        self.line_edit1.setText("")
        self.line_edit1.show()

        self.label1 = QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(20, 120, 71, 20))
        self.label1.setText("Cantiatea:")
        self.label1.show()

        self.line_edit2 = QLineEdit(self.widget)
        self.line_edit2.setGeometry(QtCore.QRect(140, 150, 201, 22))
        self.line_edit2.setText("")
        self.line_edit2.show()

        self.label2 = QLabel(self.widget)
        self.label2.setGeometry(QtCore.QRect(20, 150, 111, 20))
        self.label2.setText("ID comanda:")
        self.label2.show()

        self.line_edit3 = QLineEdit(self.widget)
        self.line_edit3.setGeometry(QtCore.QRect(480, 120, 201, 22))
        self.line_edit3.setText("")
        self.line_edit3.show()

        self.label3 = QLabel(self.widget)
        self.label3.setGeometry(QtCore.QRect(400, 120, 71, 20))
        self.label3.setText("ID produs:")
        self.label3.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(585,240,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.show()

    def show(self):
        self.widget.show()


class Produse_ui_InsertWindow(ui_InsertWindow):
    def __init__(self,widget,controler):
        super().__init__(widget,controler)
        self.setupUi(self.widget)
        self.label_title = None
        self.label_instruction = None
        self.line_edit1 = None
        self.line_edit2 = None
        self.line_edit3 = None
        self.line_edit4 = None
        self.line_edit5 = None

        self.label1 = None
        self.label2 = None
        self.label3 = None
        self.label4 = None
        self.label5 = None

        self.submit_button = None

    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 304)

        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10, 10, 168, 31))
        self.label_title.setText("Produse")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10, 70, 191, 20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        self.line_edit1 = QLineEdit(self.widget)
        self.line_edit1.setGeometry(QtCore.QRect(140, 120, 191, 22))
        self.line_edit1.setText("")
        self.line_edit1.show()

        self.label1 = QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(20, 120, 71, 20))
        self.label1.setText("Nume:")
        self.label1.show()

        self.line_edit2 = QLineEdit(self.widget)
        self.line_edit2.setGeometry(QtCore.QRect(140, 150, 191, 22))
        self.line_edit2.setText("")
        self.line_edit2.show()

        self.label2 = QLabel(self.widget)
        self.label2.setGeometry(QtCore.QRect(20, 150, 111, 20))
        self.label2.setText("Tip cantitate:")
        self.label2.show()

        self.line_edit3 = QLineEdit(self.widget)
        self.line_edit3.setGeometry(QtCore.QRect(140, 180, 191, 22))
        self.line_edit3.setText("")
        self.line_edit3.show()

        self.label3 = QLabel(self.widget)
        self.label3.setGeometry(QtCore.QRect(20, 180, 111, 20))
        self.label3.setText("Cantitate pe stoc:")
        self.label3.show()

        self.line_edit4 = QLineEdit(self.widget)
        self.line_edit4.setGeometry(QtCore.QRect(480, 120, 201, 22))
        self.line_edit4.setText("")
        self.line_edit4.show()

        self.label4 = QLabel(self.widget)
        self.label4.setGeometry(QtCore.QRect(360, 120, 111, 20))
        self.label4.setText("Ultima modificare:")
        self.label4.show()

        self.line_edit5 = QLineEdit(self.widget)
        self.line_edit5.setGeometry(QtCore.QRect(480, 150, 201, 22))
        self.line_edit5.setText("")
        self.line_edit5.show()

        self.label5 = QLabel(self.widget)
        self.label5.setGeometry(QtCore.QRect(360, 150, 111, 20))
        self.label5.setText("Pret/unitate:")
        self.label5.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(585,240,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.show()

    def show(self):
        self.widget.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InsertWindow = QtWidgets.QWidget()
    ui = ui_InsertWindow(InsertWindow)
    ui.setupUi(InsertWindow)
    InsertWindow.show()
    sys.exit(app.exec_())


class Categorii_produse_ui_InsertWindow(ui_InsertWindow):
    def __init__(self,widget,controler):
        super().__init__(widget,controler)
        self.label_title = None
        self.label_instruction = None
        self.line_edit1 = None

        self.label1 = None
        self.submit_button = None

        self.setupUi(self.widget)

    def setupUi(self, InsertWindow):
        InsertWindow.resize(703, 208)
        self.label_title = QLabel(self.widget)
        self.label_title.setGeometry(QtCore.QRect(10,10,91,31))
        self.label_title.setText("Categorii_produse")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(14)
        self.label_title.setFont(font)
        self.label_title.show()

        self.label_instruction = QLabel(self.widget)
        self.label_instruction.setGeometry(QtCore.QRect(10,70,191,20))
        self.label_instruction.setText("Introduceti datele: ")
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(10)
        self.label_instruction.setFont(font)
        self.label_instruction.show()

        self.line_edit1 = QLineEdit(self.widget)
        self.line_edit1.setGeometry(QtCore.QRect(100, 120, 181, 22))
        self.line_edit1.setText("")
        self.line_edit1.show()

        self.label1 = QLabel(self.widget)
        self.label1.setGeometry(QtCore.QRect(20, 120, 71, 16))
        self.label1.setText("Nume:")
        self.label1.show()

        self.submit_button = QtWidgets.QPushButton(self.widget)
        self.submit_button.setGeometry(QtCore.QRect(580,160,93,28))
        self.submit_button.setText("Submit")
        self.submit_button.show()
        self.submit_button.clicked.connect(self.insert_data)

    def show(self):
        self.widget.show()

    def insert_data(self):
        name = "'"+self.line_edit1.currentText()+"'"
        self.controler.cursor.execute(f'SELECT id_dept from departamente where nume={name}')

        for i in self.controler.cursor:
            dept_id = i[0]

        self.data = [name]

        result = self.controler.insert_into_table('Categorii_produse',self.data)
        if result == -1:
            self.display_popup(-1)
        elif result == -2:
            self.display_popup(-2)
        else:
            self.widget.close()
        # verificare nume email si id dept valide
